# Generated by Django 4.2.20 on 2025-03-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["last_name", "first_name"]},
        ),
    ]
